### ISSUE TITLE
Allow empty array to disable options like failOnHttpStatusCodes

### ISSUE THREAD

**Issue by Jean-Beru** [sensiolabs/GotenbergBundle#76]
So, I can't disable it. Maybe it will be interesting to allow `[]` as a valid value and `null` to use default.

_Originally posted by @Jean-Beru in https://github.com/sensiolabs/GotenbergBundle/pull/49#discussion_r1647548763_

**Comment by Neirda24** [comment]
Maybe set to `null` or a method `unset(string $key)` WDYT ?

**Comment by Jean-Beru** [comment]
IMO, `failOnHttpStatusCodes` should consider an empty array as a correct value:
- `null` => default http status codes
- `[]` => no http status codes
- `[...]` =>selected status codes

**Comment by Jean-Beru** [comment]
Sure! If Gotenberg doesn't care, this issue is useless :-/

**Comment by Neirda24** [comment]
Just tried it. It works. So yes : 
* `null` should unset the value from being sent.
* `[]` already works and overrides the default so it allows pages like `404` to render as PDF.

Checking on configuration if it is possible.
